### ISSUE TITLE
[FEAT] 서울 실시간 도시데이터 - 인구 API를 위한 기본 정보 불러오기

### ISSUE THREAD

**Issue by biiit4894** [WhatSEOUL/WhatSeoul#10]
## 📖 Describe
 서울 실시간 도시데이터 - 인구 API 구현을 위한 기본 정보를 불러옵니다

## ✅ TODO

- [x] 장소 혼잡도 지표
- [x] 장소 혼잡도 지표 관련 메시지
- [x] 실시간 인구 데이터 업데이트 시간
