### ISSUE TITLE
[FEAT] 서울 실시간 도시데이터 - 문화 행사 API 구현

### ISSUE THREAD

**Issue by ch0Changhyun** [WhatSEOUL/WhatSeoul#14]
## 📖 Describe
서울 실시간 도시데이터 - 문화 행사 API 구현
## ✅ TODO

- [x] 문화 행사 명
- [x] 문화 행사 기간
- [x] 문화 행사 장소
- [x] 문화 행사 상세 정보
