### ISSUE TITLE
[FEAT] 로그인/회원가입 1

### ISSUE THREAD

**Issue by gyenug** [WhatSEOUL/WhatSeoul#15]
## ✅ TODO

- [ ] TODO User.java
- [ ] TODO UserRepository.java
- [ ] TODO UserDetailService.java
