### ISSUE TITLE
[FEAT] 서울 실시간 도시데이터 - 날씨 API 구현2

### ISSUE THREAD

**Issue by soogoori** [WhatSEOUL/WhatSeoul#17]
## 📖 Describe
서울 실시간 도시데이터 - 날씨 API 구현

## ✅ TODO

- [x] 날씨 데이터 원하는 값만 추출
- [x] xml 데이터 가져올 때 성능 개선 시키기
- [x] 인구, 문화 정보 API 합치기

**Comment by soogoori** [comment]
- 문화행사 정보는 아직 합치지 않았습니다
- area_code에 id가 들어가는듯해서 이 부분은 수정해야할 것 같아요
