### ISSUE TITLE
[FEAT] 서울 실시간 도시데이터 - 인구데이터 조회 API 구현

### ISSUE THREAD

**Issue by biiit4894** [WhatSEOUL/WhatSeoul#23]
## 📖 Describe
- 스케줄러에 의해 db에 저장되는 도시데이터를 바탕으로 지역별 인구데이터를 조회하는 api를 구현합니다

## ✅ TODO
- [x] 인구 관련 기본 정보 조회
- [x] 인구 관련 예측 정보 전체 조회
- [x] 인구 관련 예측 정보 기획에 맞게 파싱 -> 가장 붐비는 시간대 보여주기 어려울것같아서.. 최소 최대인구 지표 보여주기
