### ISSUE TITLE
[FEAT] 지역 선택 ui 수정

### ISSUE THREAD

**Issue by biiit4894** [WhatSEOUL/WhatSeoul#62]
## 📖 Describe
- 지역구를 고른 후 지역(핫스팟)을 고르는 ui를 개선합니다

## ✅ TODO
- [x] 카카오맵 api 연동
- [x] 지역별 위치 및 특색(명소) 정보 저장 api 구현 
- [x] 개별/복수 지역정보 조회 api 구현
