### ISSUE TITLE
[FEAT] 서울 실시간 도시데이터 - 날씨 API 구현

### ISSUE THREAD

**Issue by soogoori** [WhatSEOUL/WhatSeoul#9]
## 📖 Describe
 서울 실시간 도시데이터 - 날씨 API 구현

## ✅ TODO

- [x] 기온
- [x] 일 최고/최저 온도
- [x] 강수형태
- [x] 미세먼지 관련 데이터
- [x] 날씨 데이터 업데이트 시간
- [ ] 하늘 상태
- [ ] scheduler 사용해서 15분 주기로 업데이트

**Comment by soogoori** [comment]
- 하늘 상태는 제외!
- 15분 주기로 할지는 아직 미정
